/rm_serial_driver:
  ros__parameters:
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"
    cmd_vel_linear_scale: 0.4
    nav_packet_version: 2
    follow_mark_timeout_sec: 0.5
